server:
  port: 9999
spring:
  datasource:
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.3:3306/mydb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  application:
    name: cloud-gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      enabled: true
      routes:
        - id: cloud-product
          uri: lb://cloud-product
          predicates:
            - Path=/product/**
          filters:
            - Authorize=true
            #- StripPrefix=1
        - id: cloud-user
          uri: lb://cloud-user
          predicates:
            - Path=/user/**
          filters:
            - AddResponseHeader=X-Response-Foo, Bar
            - Authorize=true
            #- StripPrefix=1
verify:
  whites:
    -white: /user/newsList


